//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VOCATION_MVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Vacation_DBEntities : DbContext
    {
        public Vacation_DBEntities()
            : base("name=Vacation_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Tbl_Account> Tbl_Account { get; set; }
        public virtual DbSet<Tbl_Departments> Tbl_Departments { get; set; }
        public virtual DbSet<Tbl_Persons> Tbl_Persons { get; set; }
        public virtual DbSet<Tbl_Positions> Tbl_Positions { get; set; }
        public virtual DbSet<Tbl_Rols> Tbl_Rols { get; set; }
        public virtual DbSet<Tbl_UseVacationCount> Tbl_UseVacationCount { get; set; }
        public virtual DbSet<Tbl_VacationAppeals> Tbl_VacationAppeals { get; set; }
        public virtual DbSet<Tbl_VacationDays> Tbl_VacationDays { get; set; }
    }
}
