//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VOCATION_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Persons
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Persons()
        {
            this.Tbl_Account = new HashSet<Tbl_Account>();
            this.Tbl_UseVacationCount = new HashSet<Tbl_UseVacationCount>();
            this.Tbl_VacationAppeals = new HashSet<Tbl_VacationAppeals>();
        }
    
        public int id { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public int PositionId { get; set; }
        public int DepartmentId { get; set; }
        public int RoleId { get; set; }
        public System.DateTime RegDate { get; set; }
        public bool IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Account> Tbl_Account { get; set; }
        public virtual Tbl_Departments Tbl_Departments { get; set; }
        public virtual Tbl_Positions Tbl_Positions { get; set; }
        public virtual Tbl_Rols Tbl_Rols { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_UseVacationCount> Tbl_UseVacationCount { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_VacationAppeals> Tbl_VacationAppeals { get; set; }
    }
}
