//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VOCATION_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Positions
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Positions()
        {
            this.Tbl_Persons = new HashSet<Tbl_Persons>();
            this.Tbl_VacationDays = new HashSet<Tbl_VacationDays>();
        }
    
        public int id { get; set; }
        public Nullable<System.DateTime> RegDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string Position { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Persons> Tbl_Persons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_VacationDays> Tbl_VacationDays { get; set; }
    }
}
