//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VOCATION_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_VacationDays
    {
        public int id { get; set; }
        public int DayCount { get; set; }
        public int PositionId { get; set; }
        public string Note { get; set; }
        public System.DateTime RegDate { get; set; }
    
        public virtual Tbl_Positions Tbl_Positions { get; set; }
    }
}
