//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VOCATION_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_UseVacationCount
    {
        public int id { get; set; }
        public int PersonId { get; set; }
        public int UsedVacationDaysCount { get; set; }
        public System.DateTime Regdate { get; set; }
    
        public virtual Tbl_Persons Tbl_Persons { get; set; }
    }
}
